// dotname generate — reads .dag, generates Solidity contracts
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

interface DagNode {
  i: string;  // id
  t: string;  // type (entity, contract, event)
  g: string;  // category
  d: string;  // description
  p: Record<string, string>; // properties (compact encoding)
  s: string[]; // states
  l: string[]; // lifecycle transitions
}

interface DagEdge {
  s: string; // source
  t: string; // target
  v: string; // verb
  d: string; // description
  c: string; // cardinality
  r: boolean; // required
}

interface DagFile {
  v: string; // version
  p: string; // project
  n: DagNode[]; // nodes
  e: DagEdge[]; // edges
}

const PROP_MAP: Record<string, string> = {
  's': 'string',
  's!': 'string',
  'n': 'uint256',
  'n!': 'uint256',
  'b': 'bool',
  'b!': 'bool',
  'e': 'uint8',
  'e!': 'uint8',
  'j': 'string',
  'j!': 'string',
};

function decodeProp(enc: string): string {
  return PROP_MAP[enc] || 'string';
}

function toPascalCase(s: string): string {
  return s.replace(/[-_\s]+(.)?/g, (_, c) => c ? c.toUpperCase() : '')
    .replace(/^./, c => c.toUpperCase());
}

function toCamelCase(s: string): string {
  return s.replace(/[-_\s]+(.)?/g, (_, c) => c ? c.toUpperCase() : '')
    .replace(/^./, c => c.toLowerCase());
}

function generateContract(node: DagNode, edges: DagEdge[]): string {
  const name = toPascalCase(node.i);
  const camelName = toCamelCase(node.i);
  
  // Find related edges
  const outgoing = edges.filter(e => e.s === node.i);
  const incoming = edges.filter(e => e.t === node.i);
  
  let code = `// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec
// Entity: ${node.i} — ${node.d}
pragma solidity ^0.8.20;\n\n`;
  
  // Imports
  code += `import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";\n\n`;
  
  // State enum
  if (node.s.length > 0) {
    code += `enum ${name}State { ${node.s.map(s => toPascalCase(s)).join(', ')} }\n\n`;
  }
  
  // Event for state changes
  if (node.s.length > 0) {
    code += `event StateChanged(${name}State from, ${name}State to);\n\n`;
  }
  
  // Contract
  code += `contract ${name} is Ownable {\n`;
  
  // Properties as storage
  for (const [propName, enc] of Object.entries(node.p)) {
    const solType = decodeProp(enc);
    code += `    ${solType} public ${toCamelCase(propName)};\n`;
  }
  
  // State tracking
  if (node.s.length > 0) {
    code += `\n    ${name}State public state;\n`;
  }
  
  // Constructor
  code += `\n    constructor() Ownable(msg.sender) {\n`;
  if (node.s.length > 0) {
    code += `        state = ${name}State.${toPascalCase(node.s[0])};\n`;
  }
  code += `    }\n\n`;
  
  // State transition functions from lifecycle
  for (const transition of node.l) {
    const [from, to] = transition.split(/\s*→\s*/);
    if (!from || !to) continue;
    const funcName = toCamelCase(to);
    code += `    function ${funcName}() external onlyOwner {\n`;
    code += `        require(state == ${name}State.${toPascalCase(from)}, "Invalid state");\n`;
    code += `        ${name}State _prev = state;\n`;
    code += `        state = ${name}State.${toPascalCase(to)};\n`;
    code += `        emit StateChanged(_prev, state);\n`;
    code += `    }\n\n`;
  }
  
  // Relationship methods
  for (const e of outgoing) {
    const verb = toCamelCase(e.v);
    const target = toPascalCase(e.t);
    code += `    // ${e.v} → ${e.t}: ${e.d}\n`;
    code += `    function ${verb}${target}() external view returns (address) {\n`;
    code += `        // TODO: implement ${e.v} relationship\n`;
    code += `        return address(0);\n`;
    code += `    }\n\n`;
  }
  
  code += `}\n`;
  return code;
}

export function generate(dir: string, project: string): { files: string[], output: string } {
  const dagFile = join(dir, 'specs', project, `${project}.dag`);
  if (!existsSync(dagFile)) throw new Error(`No .dag found. Run 'dotdog compile' first.`);
  
  const dag: DagFile = JSON.parse(readFileSync(dagFile, 'utf-8'));
  const nodes = dag.n || [];
  const edges = dag.e || [];
  
  const outDir = join(dir, 'contracts', 'src');
  mkdirSync(outDir, { recursive: true });
  
  const generated: string[] = [];
  
  for (const node of nodes) {
    if (node.t === 'contract' || node.g === 'contract') {
      const code = generateContract(node, edges);
      const fileName = `${toPascalCase(node.i)}.sol`;
      writeFileSync(join(outDir, fileName), code, 'utf-8');
      generated.push(fileName);
    }
  }
  
  // Write deployment script
  let deployScript = `// Deploy script for ${project} on Base Sepolia
import { ethers } from "hardhat";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying from:", deployer.address);\n\n`;
  
  for (const node of nodes) {
    if (node.t === 'contract' || node.g === 'contract') {
      const name = toPascalCase(node.i);
      deployScript += `  const ${toCamelCase(node.i)} = await ethers.deployContract("${name}");\n`;
      deployScript += `  await ${toCamelCase(node.i)}.waitForDeployment();\n`;
      deployScript += `  console.log("${name} deployed to:", await ${toCamelCase(node.i)}.getAddress());\n\n`;
    }
  }
  
  deployScript += `}\n\nmain().catch(console.error);\n`;
  writeFileSync(join(dir, 'contracts', 'deploy.ts'), deployScript, 'utf-8');
  
  return {
    files: generated,
    output: outDir,
  };
}
