// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec — A user's onchain identity. Stores name, avatar, bio, and verified links.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum ProfileState { Created, Active, Suspended }

event StateChanged(ProfileState from, ProfileState to);

contract Profile is Ownable {
    string public address;
    string public name;
    string public avatar;
    string public bio;
    string public links;
    string public owner;

    ProfileState public state;

    constructor() Ownable(msg.sender) {
        state = ProfileState.Created;
    }

    function active() external onlyOwner {
        require(state == ProfileState.Created, "Invalid state");
        ProfileState _prev = state;
        state = ProfileState.Active;
        emit StateChanged(_prev, state);
    }

    function suspended() external onlyOwner {
        require(state == ProfileState.Active, "Invalid state");
        ProfileState _prev = state;
        state = ProfileState.Suspended;
        emit StateChanged(_prev, state);
    }

    // deployed_on → Base
    address public baseContract;

}
