// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec
// Entity: Profile — A user's onchain identity. Stores name, avatar, bio, and verified links.
// Part of onchain identity protocol. Deployed on Base. Resolved via ENS.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum ProfileState { Created, Active, Suspended }

event StateChanged(ProfileState from, ProfileState to);

/// @title Profile
/// @notice A user's onchain identity. Stores name, avatar, bio, and verified links.
/// @dev Generated from .dog spec. Deployed on Base Sepolia.
contract Profile is Ownable {
    string public address;
    string public name;
    string public avatar;
    string public bio;
    string public links;
    string public owner;

    ProfileState public state;

    constructor() Ownable(msg.sender) {
        state = ProfileState.Created;
    }

    function active() external onlyOwner {
        require(state == ProfileState.Created, "Invalid state");
        ProfileState _prev = state;
        state = ProfileState.Active;
        emit StateChanged(_prev, state);
    }

    function suspended() external onlyOwner {
        require(state == ProfileState.Active, "Invalid state");
        ProfileState _prev = state;
        state = ProfileState.Suspended;
        emit StateChanged(_prev, state);
    }

    /// @notice deployed_on Base
    /// @dev All contracts deployed on Base Sepolia L2
    address public baseContract;

}
