// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec
// Entity: Registry — ENS-compatible registry mapping names to profile addresses.
// Part of onchain identity protocol. Deployed on Base. Resolved via ENS.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum RegistryState { Deployed, Active }

event StateChanged(RegistryState from, RegistryState to);

/// @title Registry
/// @notice ENS-compatible registry mapping names to profile addresses.
/// @dev Generated from .dog spec. Deployed on Base Sepolia.
contract Registry is Ownable {
    string public address;
    string public owner;

    RegistryState public state;

    constructor() Ownable(msg.sender) {
        state = RegistryState.Deployed;
    }

    function active() external onlyOwner {
        require(state == RegistryState.Deployed, "Invalid state");
        RegistryState _prev = state;
        state = RegistryState.Active;
        emit StateChanged(_prev, state);
    }

    /// @notice maps Profile
    /// @dev Registry maps ENS names to profile addresses
    address public profileContract;

}
