// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec
// Entity: Registrar — Subdomain registrar for base.eth. Users register `name.base.eth` subdomains.
// Part of onchain identity protocol. Deployed on Base. Resolved via ENS.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum RegistrarState { Deployed, Active }

event StateChanged(RegistrarState from, RegistrarState to);

/// @title Registrar
/// @notice Subdomain registrar for base.eth. Users register `name.base.eth` subdomains.
/// @dev Generated from .dog spec. Deployed on Base Sepolia.
contract Registrar is Ownable {
    string public address;
    string public parentDomain;
    uint256 public registrationFee;

    RegistrarState public state;

    constructor() Ownable(msg.sender) {
        state = RegistrarState.Deployed;
    }

    function active() external onlyOwner {
        require(state == RegistrarState.Deployed, "Invalid state");
        RegistrarState _prev = state;
        state = RegistrarState.Active;
        emit StateChanged(_prev, state);
    }

    /// @notice creates Profile
    /// @dev Registering a name creates a profile
    address public profileContract;

}
