// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec — Subdomain registrar for base.eth. Users register `name.base.eth` subdomains.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum RegistrarState { Deployed, Active }

event StateChanged(RegistrarState from, RegistrarState to);

contract Registrar is Ownable {
    string public address;
    string public parentDomain;
    uint256 public registrationFee;

    RegistrarState public state;

    constructor() Ownable(msg.sender) {
        state = RegistrarState.Deployed;
    }

    function active() external onlyOwner {
        require(state == RegistrarState.Deployed, "Invalid state");
        RegistrarState _prev = state;
        state = RegistrarState.Active;
        emit StateChanged(_prev, state);
    }

    // creates → Profile
    address public profileContract;

}
