// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec — ENS-compatible registry mapping names to profile addresses.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum RegistryState { Deployed, Active }

event StateChanged(RegistryState from, RegistryState to);

contract Registry is Ownable {
    string public address;
    string public owner;

    RegistryState public state;

    constructor() Ownable(msg.sender) {
        state = RegistryState.Deployed;
    }

    function active() external onlyOwner {
        require(state == RegistryState.Deployed, "Invalid state");
        RegistryState _prev = state;
        state = RegistryState.Active;
        emit StateChanged(_prev, state);
    }

    // maps → Profile
    address public profileContract;

}
