// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec — ENS resolver that returns profile metadata for a given name.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum ResolverState { Deployed, Active }

event StateChanged(ResolverState from, ResolverState to);

contract Resolver is Ownable {
    string public address;

    ResolverState public state;

    constructor() Ownable(msg.sender) {
        state = ResolverState.Deployed;
    }

    function active() external onlyOwner {
        require(state == ResolverState.Deployed, "Invalid state");
        ResolverState _prev = state;
        state = ResolverState.Active;
        emit StateChanged(_prev, state);
    }

    // resolves → Profile
    address public profileContract;

}
