// SPDX-License-Identifier: MIT
// Generated by dotname from .dog spec
// Entity: Resolver — ENS resolver that returns profile metadata for a given name.
// Part of onchain identity protocol. Deployed on Base. Resolved via ENS.
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

enum ResolverState { Deployed, Active }

event StateChanged(ResolverState from, ResolverState to);

/// @title Resolver
/// @notice ENS resolver that returns profile metadata for a given name.
/// @dev Generated from .dog spec. Deployed on Base Sepolia.
contract Resolver is Ownable {
    string public address;

    ResolverState public state;

    constructor() Ownable(msg.sender) {
        state = ResolverState.Deployed;
    }

    function active() external onlyOwner {
        require(state == ResolverState.Deployed, "Invalid state");
        ResolverState _prev = state;
        state = ResolverState.Active;
        emit StateChanged(_prev, state);
    }

    /// @notice resolves Profile
    /// @dev Resolver returns profile metadata for ENS lookups
    address public profileContract;

}
